import 'models.dart';

class DistributorNotice {
  const DistributorNotice({
    required this.id,
    required this.title,
    required this.message,
    required this.createdAt,
  });

  final String id;
  final String title;
  final String message;
  final DateTime createdAt;
}

const List<Product> mockProducts = [
  Product(
    id: '1',
    name: 'SCS SX Pro Elite',
    category: ProductCategory.headset,
    sku: 'SCS-SX-PRO-ELITE',
    shortDescription:
        'Tai nghe gaming flagship voi ANC chu dong, am thanh vong 7.1 va driver 50mm.',
    dealerPrice: 4912000,
    listPrice: 5990000,
    stock: 120,
    warrantyMonths: 24,
    imageUrl: 'https://picsum.photos/seed/dealer-1/800/800',
    descriptions: [
      ProductDescriptionItem(
        type: ProductDescriptionType.title,
        text: 'Diem noi bat',
      ),
      ProductDescriptionItem(
        type: ProductDescriptionType.description,
        text:
            'SX Pro Elite toi uu cho gaming va stream voi ANC chu dong, do tre thap va do ben cao.',
      ),
      ProductDescriptionItem(
        type: ProductDescriptionType.image,
        url: 'https://picsum.photos/seed/dealer-1-detail/1280/720',
        caption: 'Thiet ke gon gang, trong luong nhe cho su dung lau dai.',
      ),
    ],
    videos: [
      ProductVideoItem(
        title: 'SX Pro Elite Overview',
        url:
            'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
        description: 'Tong quan tinh nang va huong dan ket noi nhanh.',
      ),
    ],
    minOrderQty: 1,
    orderStep: 1,
    isOrderable: true,
    specifications: [
      ProductSpecification(label: 'Driver', value: '50mm'),
      ProductSpecification(label: 'Ket noi', value: 'USB + 3.5mm'),
      ProductSpecification(label: 'Am thanh', value: '7.1 Virtual'),
    ],
  ),
  Product(
    id: '2',
    name: 'SCS SX Wireless Pro',
    category: ProductCategory.headset,
    sku: 'SCS-SX-WIRELESS-PRO',
    shortDescription: 'Khong day do tre thap, pin 30 gio, 2.4G + Bluetooth.',
    dealerPrice: 3682000,
    listPrice: 4490000,
    stock: 64,
    warrantyMonths: 18,
    imageUrl: 'https://picsum.photos/seed/dealer-2/800/800',
    minOrderQty: 1,
    orderStep: 1,
    isOrderable: true,
    specifications: [
      ProductSpecification(label: 'Driver', value: '40mm'),
      ProductSpecification(label: 'Pin', value: '30h'),
      ProductSpecification(label: 'Ket noi', value: '2.4G + BT 5.2'),
    ],
  ),
  Product(
    id: '3',
    name: 'SCS Professional Studio',
    category: ProductCategory.headset,
    sku: 'SCS-PRO-STUDIO',
    shortDescription:
        'Tai nghe kiem am can bang, trung thuc, phu hop phong thu.',
    dealerPrice: 2698000,
    listPrice: 3290000,
    stock: 14,
    warrantyMonths: 18,
    imageUrl: 'https://picsum.photos/seed/dealer-3/800/800',
    minOrderQty: 2,
    orderStep: 2,
    isOrderable: true,
    specifications: [
      ProductSpecification(label: 'Driver', value: '45mm'),
      ProductSpecification(label: 'Tro khang', value: '32Ohm'),
      ProductSpecification(label: 'Day', value: 'Detachable'),
    ],
  ),
  Product(
    id: '5',
    name: 'SCS Nova Air',
    category: ProductCategory.headset,
    sku: 'SCS-NOVA-AIR',
    shortDescription:
        'Lightweight wireless headset with 2.4G + BT and 45mm driver.',
    dealerPrice: 3108000,
    listPrice: 3790000,
    stock: 80,
    warrantyMonths: 18,
    imageUrl: 'https://picsum.photos/seed/dealer-5/800/800',
    minOrderQty: 2,
    orderStep: 2,
    isOrderable: true,
    specifications: [
      ProductSpecification(label: 'Driver', value: '45mm'),
      ProductSpecification(label: 'Connectivity', value: '2.4G + BT 5.2'),
      ProductSpecification(label: 'Battery', value: '28h'),
    ],
  ),
  Product(
    id: '6',
    name: 'SCS Nova Air Lite',
    category: ProductCategory.headset,
    sku: 'SCS-NOVA-AIR-LITE',
    shortDescription:
        'Compact wireless headset with 2.4G dongle and foldable design.',
    dealerPrice: 2288000,
    listPrice: 2790000,
    stock: 32,
    warrantyMonths: 12,
    imageUrl: 'https://picsum.photos/seed/dealer-6/800/800',
    minOrderQty: 2,
    orderStep: 2,
    isOrderable: true,
    specifications: [
      ProductSpecification(label: 'Driver', value: '40mm'),
      ProductSpecification(label: 'Latency', value: '< 30ms'),
      ProductSpecification(label: 'Weight', value: '230g'),
    ],
  ),
  Product(
    id: '7',
    name: 'SCS Bass Titan',
    category: ProductCategory.headset,
    sku: 'SCS-BASS-TITAN',
    shortDescription:
        'Deep bass gaming headset with reinforced frame and 7.1 mode.',
    dealerPrice: 4338000,
    listPrice: 5290000,
    stock: 9,
    warrantyMonths: 24,
    imageUrl: 'https://picsum.photos/seed/dealer-7/800/800',
    minOrderQty: 1,
    orderStep: 1,
    isOrderable: true,
    specifications: [
      ProductSpecification(label: 'Driver', value: '50mm'),
      ProductSpecification(label: 'Surround', value: '7.1 Virtual'),
      ProductSpecification(label: 'Frame', value: 'Aluminum'),
    ],
  ),
  Product(
    id: '8',
    name: 'SCS Stream Pro Mic',
    category: ProductCategory.accessory,
    sku: 'SCS-STREAM-PRO-MIC',
    shortDescription: 'USB condenser mic with cardioid mode and tap-to-mute.',
    dealerPrice: 1796000,
    listPrice: 2190000,
    stock: 25,
    warrantyMonths: 12,
    imageUrl: 'https://picsum.photos/seed/dealer-8/800/800',
    minOrderQty: 2,
    orderStep: 2,
    isOrderable: true,
    specifications: [
      ProductSpecification(label: 'Pattern', value: 'Cardioid'),
      ProductSpecification(label: 'Interface', value: 'USB-C'),
      ProductSpecification(label: 'Sample Rate', value: '96kHz'),
    ],
  ),
  Product(
    id: '10',
    name: 'SCS RGB Key Pro',
    category: ProductCategory.keyboard,
    sku: 'SCS-RGB-KEY-PRO',
    shortDescription: 'Full-size mechanical keyboard with hot-swap switches.',
    dealerPrice: 1550000,
    listPrice: 1890000,
    stock: 140,
    warrantyMonths: 12,
    imageUrl: 'https://picsum.photos/seed/dealer-10/800/800',
    minOrderQty: 5,
    orderStep: 5,
    isOrderable: true,
    specifications: [
      ProductSpecification(label: 'Layout', value: '104 keys'),
      ProductSpecification(label: 'Switch', value: 'Hot-swap'),
      ProductSpecification(label: 'Plate', value: 'Aluminum'),
    ],
  ),
  Product(
    id: '11',
    name: 'SCS RGB Key Lite',
    category: ProductCategory.keyboard,
    sku: 'SCS-RGB-KEY-LITE',
    shortDescription:
        'Tenkeyless keyboard with silent switches and simple lighting.',
    dealerPrice: 976000,
    listPrice: 1190000,
    stock: 12,
    warrantyMonths: 12,
    imageUrl: 'https://picsum.photos/seed/dealer-11/800/800',
    minOrderQty: 5,
    orderStep: 5,
    isOrderable: true,
    specifications: [
      ProductSpecification(label: 'Layout', value: '87 keys'),
      ProductSpecification(label: 'Switch', value: 'Silent linear'),
      ProductSpecification(label: 'Cable', value: 'Detachable'),
    ],
  ),
  Product(
    id: '12',
    name: 'SCS Control Mouse X1',
    category: ProductCategory.mouse,
    sku: 'SCS-CONTROL-MOUSE-X1',
    shortDescription: 'Ergonomic wired mouse with 6 buttons and PTFE feet.',
    dealerPrice: 812000,
    listPrice: 990000,
    stock: 55,
    warrantyMonths: 12,
    imageUrl: 'https://picsum.photos/seed/dealer-12/800/800',
    minOrderQty: 10,
    orderStep: 10,
    isOrderable: true,
    specifications: [
      ProductSpecification(label: 'Sensor', value: 'Pixart 3327'),
      ProductSpecification(label: 'Buttons', value: '6'),
      ProductSpecification(label: 'Weight', value: '72g'),
    ],
  ),
  Product(
    id: '13',
    name: 'SCS Control Mouse X1 Wireless',
    category: ProductCategory.mouse,
    sku: 'SCS-CONTROL-MOUSE-X1-WL',
    shortDescription: 'Wireless mouse with 2.4G + BT and 90h battery.',
    dealerPrice: 1222000,
    listPrice: 1490000,
    stock: 7,
    warrantyMonths: 12,
    imageUrl: 'https://picsum.photos/seed/dealer-13/800/800',
    minOrderQty: 5,
    orderStep: 5,
    isOrderable: true,
    specifications: [
      ProductSpecification(label: 'Connectivity', value: '2.4G + BT'),
      ProductSpecification(label: 'Battery', value: '90h'),
      ProductSpecification(label: 'Weight', value: '78g'),
    ],
  ),
  Product(
    id: '14',
    name: 'SCS Pad XL',
    category: ProductCategory.accessory,
    sku: 'SCS-PAD-XL',
    shortDescription: 'Large desk pad with stitched edges and smooth surface.',
    dealerPrice: 320000,
    listPrice: 390000,
    stock: 200,
    warrantyMonths: 12,
    imageUrl: 'https://picsum.photos/seed/dealer-14/800/800',
    minOrderQty: 10,
    orderStep: 10,
    isOrderable: true,
    specifications: [
      ProductSpecification(label: 'Size', value: '900x400mm'),
      ProductSpecification(label: 'Surface', value: 'Micro-texture'),
      ProductSpecification(label: 'Base', value: 'Rubber'),
    ],
  ),
  Product(
    id: '16',
    name: 'SCS Speaker Orbit',
    category: ProductCategory.speaker,
    sku: 'SCS-SPEAKER-ORBIT',
    shortDescription: 'Desktop speakers with angled drivers and warm mids.',
    dealerPrice: 2452000,
    listPrice: 2990000,
    stock: 18,
    warrantyMonths: 12,
    imageUrl: 'https://picsum.photos/seed/dealer-16/800/800',
    minOrderQty: 2,
    orderStep: 2,
    isOrderable: true,
    specifications: [
      ProductSpecification(label: 'Power', value: '30W RMS'),
      ProductSpecification(label: 'Inputs', value: '3.5mm + USB'),
      ProductSpecification(label: 'Drivers', value: '2.75in'),
    ],
  ),
  Product(
    id: '17',
    name: 'SCS Speaker Orbit Mini',
    category: ProductCategory.speaker,
    sku: 'SCS-SPEAKER-ORBIT-MINI',
    shortDescription:
        'Compact desktop speakers with volume knob and USB power.',
    dealerPrice: 1632000,
    listPrice: 1990000,
    stock: 0,
    warrantyMonths: 12,
    imageUrl: 'https://picsum.photos/seed/dealer-17/800/800',
    minOrderQty: 5,
    orderStep: 5,
    isOrderable: false,
    specifications: [
      ProductSpecification(label: 'Power', value: '20W RMS'),
      ProductSpecification(label: 'Inputs', value: '3.5mm'),
      ProductSpecification(label: 'Power source', value: 'USB'),
    ],
  ),
  Product(
    id: '18',
    name: 'SCS Webcam Flow 4K',
    category: ProductCategory.webcam,
    sku: 'SCS-WEBCAM-FLOW-4K',
    shortDescription: '4K webcam with HDR, auto focus, and privacy shutter.',
    dealerPrice: 2124000,
    listPrice: 2590000,
    stock: 22,
    warrantyMonths: 12,
    imageUrl: 'https://picsum.photos/seed/dealer-18/800/800',
    minOrderQty: 2,
    orderStep: 2,
    isOrderable: true,
    specifications: [
      ProductSpecification(label: 'Resolution', value: '4K'),
      ProductSpecification(label: 'HDR', value: 'Yes'),
      ProductSpecification(label: 'Focus', value: 'Auto'),
    ],
  ),
];

final List<DistributorNotice> mockDistributorNotices = [
  DistributorNotice(
    id: 'notice-01',
    title: 'Cập nhật chính sách giao hàng',
    message: 'Đơn nội thành giao trong 24h. Đơn tỉnh xa giao từ 2-4 ngày.',
    createdAt: DateTime(2026, 2, 14),
  ),
  DistributorNotice(
    id: 'notice-02',
    title: 'Chương trình hỗ trợ quý I',
    message: 'Đơn từ 50 triệu được hỗ trợ POSM và tài liệu bán hàng.',
    createdAt: DateTime(2026, 2, 11),
  ),
  DistributorNotice(
    id: 'notice-03',
    title: 'Lịch bảo trì hệ thống',
    message: 'Hệ thống mock API bảo trì 23:00-23:30 Chủ Nhật.',
    createdAt: DateTime(2026, 2, 9),
  ),
];

const String distributorBankName = 'Vietcombank - CN Ha Noi';
const String distributorBankAccount = '0123456789';
const String distributorBankOwner = 'CONG TY TNHH 4THITEK';
const String distributorTransferTemplate = 'TT [MA_DAI_LY] [MA_DON_HANG]';
