--
-- PostgreSQL database dump
--

\restrict 2kzHEmICRHLQ7XAYyqLPmpBkdMooeiWxzsddRD2q6Hwrj8vpKb9IgkNrvxLXet1

-- Dumped from database version 16.13
-- Dumped by pg_dump version 16.13

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: account_roles; Type: TABLE; Schema: public; Owner: fourthitek_user
--

CREATE TABLE public.account_roles (
    account_id bigint NOT NULL,
    role_id bigint NOT NULL
);


ALTER TABLE public.account_roles OWNER TO fourthitek_user;

--
-- Name: accounts; Type: TABLE; Schema: public; Owner: fourthitek_user
--

CREATE TABLE public.accounts (
    created_at timestamp(6) with time zone,
    id bigint NOT NULL,
    updated_at timestamp(6) with time zone,
    email character varying(255),
    password character varying(255),
    username character varying(255),
    email_verified boolean DEFAULT false NOT NULL,
    email_verified_at timestamp(6) with time zone
);


ALTER TABLE public.accounts OWNER TO fourthitek_user;

--
-- Name: accounts_id_seq; Type: SEQUENCE; Schema: public; Owner: fourthitek_user
--

ALTER TABLE public.accounts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: admin_settings; Type: TABLE; Schema: public; Owner: fourthitek_user
--

CREATE TABLE public.admin_settings (
    email_confirmation boolean NOT NULL,
    inventory_alerts boolean NOT NULL,
    order_alerts boolean NOT NULL,
    session_timeout_minutes integer NOT NULL,
    created_at timestamp(6) with time zone,
    id bigint NOT NULL,
    updated_at timestamp(6) with time zone,
    sepay_enabled boolean,
    sepay_webhook_token character varying(255),
    sepay_bank_name character varying(255),
    sepay_account_number character varying(255),
    sepay_account_holder character varying(255),
    mail_enabled boolean,
    mail_from character varying(255),
    mail_from_name character varying(255),
    rate_limit_enabled boolean,
    rate_limit_auth_requests integer,
    rate_limit_auth_window_seconds bigint,
    rate_limit_password_reset_requests integer,
    rate_limit_password_reset_window_seconds bigint,
    rate_limit_warranty_lookup_requests integer,
    rate_limit_warranty_lookup_window_seconds bigint,
    rate_limit_upload_requests integer,
    rate_limit_upload_window_seconds bigint,
    rate_limit_webhook_requests integer,
    rate_limit_webhook_window_seconds bigint,
    vat_percent integer DEFAULT 10 NOT NULL
);


ALTER TABLE public.admin_settings OWNER TO fourthitek_user;

--
-- Name: admin_settings_id_seq; Type: SEQUENCE; Schema: public; Owner: fourthitek_user
--

ALTER TABLE public.admin_settings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.admin_settings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: admins; Type: TABLE; Schema: public; Owner: fourthitek_user
--

CREATE TABLE public.admins (
    id_account bigint NOT NULL,
    display_name character varying(255),
    role_title character varying(255),
    user_status character varying(64),
    require_password_change boolean DEFAULT false NOT NULL
);


ALTER TABLE public.admins OWNER TO fourthitek_user;

--
-- Name: audit_logs; Type: TABLE; Schema: public; Owner: fourthitek_user
--

CREATE TABLE public.audit_logs (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    actor character varying(255),
    actor_role character varying(255),
    action character varying(255) NOT NULL,
    request_method character varying(16) NOT NULL,
    request_path character varying(512) NOT NULL,
    entity_type character varying(255),
    entity_id character varying(255),
    ip_address character varying(128),
    payload jsonb
);


ALTER TABLE public.audit_logs OWNER TO fourthitek_user;

--
-- Name: audit_logs_id_seq; Type: SEQUENCE; Schema: public; Owner: fourthitek_user
--

ALTER TABLE public.audit_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.audit_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: blogs; Type: TABLE; Schema: public; Owner: fourthitek_user
--

CREATE TABLE public.blogs (
    is_deleted boolean,
    show_on_homepage boolean,
    created_at timestamp(6) with time zone,
    id bigint NOT NULL,
    id_category_blog bigint,
    updated_at timestamp(6) with time zone,
    description text,
    title character varying(255),
    image jsonb,
    introduction jsonb,
    status character varying(64),
    scheduled_at timestamp with time zone
);


ALTER TABLE public.blogs OWNER TO fourthitek_user;

--
-- Name: blogs_id_seq; Type: SEQUENCE; Schema: public; Owner: fourthitek_user
--

ALTER TABLE public.blogs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.blogs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: bulk_discounts; Type: TABLE; Schema: public; Owner: fourthitek_user
--

CREATE TABLE public.bulk_discounts (
    discount_percent numeric(38,2),
    created_at timestamp(6) with time zone,
    id bigint NOT NULL,
    updated_at timestamp(6) with time zone,
    status character varying(64),
    from_quantity integer,
    to_quantity integer
);


ALTER TABLE public.bulk_discounts OWNER TO fourthitek_user;

--
-- Name: bulk_discounts_id_seq; Type: SEQUENCE; Schema: public; Owner: fourthitek_user
--

ALTER TABLE public.bulk_discounts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bulk_discounts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: category_blogs; Type: TABLE; Schema: public; Owner: fourthitek_user
--

CREATE TABLE public.category_blogs (
    id bigint NOT NULL,
    name character varying(255)
);


ALTER TABLE public.category_blogs OWNER TO fourthitek_user;

--
-- Name: category_blogs_id_seq; Type: SEQUENCE; Schema: public; Owner: fourthitek_user
--

ALTER TABLE public.category_blogs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.category_blogs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: customers; Type: TABLE; Schema: public; Owner: fourthitek_user
--

CREATE TABLE public.customers (
    id_account bigint NOT NULL,
    avatar_url character varying(2000),
    full_name character varying(255),
    phone character varying(255)
);


ALTER TABLE public.customers OWNER TO fourthitek_user;

--
-- Name: dealer_cart_items; Type: TABLE; Schema: public; Owner: fourthitek_user
--

CREATE TABLE public.dealer_cart_items (
    quantity integer,
    created_at timestamp(6) with time zone,
    id_dealer bigint NOT NULL,
    id_product_of_cart bigint NOT NULL,
    updated_at timestamp(6) with time zone
);


ALTER TABLE public.dealer_cart_items OWNER TO fourthitek_user;

--
-- Name: dealer_support_tickets; Type: TABLE; Schema: public; Owner: fourthitek_user
--

CREATE TABLE public.dealer_support_tickets (
    closed_at timestamp(6) with time zone,
    created_at timestamp(6) with time zone,
    dealer_id bigint NOT NULL,
    id bigint NOT NULL,
    resolved_at timestamp(6) with time zone,
    updated_at timestamp(6) with time zone,
    admin_reply text,
    message text NOT NULL,
    subject character varying(255) NOT NULL,
    ticket_code character varying(255) NOT NULL,
    category character varying(64) NOT NULL,
    priority character varying(64) NOT NULL,
    status character varying(64) NOT NULL,
    assignee_id bigint,
    context_data text
);


ALTER TABLE public.dealer_support_tickets OWNER TO fourthitek_user;

--
-- Name: dealer_support_tickets_id_seq; Type: SEQUENCE; Schema: public; Owner: fourthitek_user
--

ALTER TABLE public.dealer_support_tickets ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.dealer_support_tickets_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: dealers; Type: TABLE; Schema: public; Owner: fourthitek_user
--

CREATE TABLE public.dealers (
    credit_limit numeric(38,2),
    id_account bigint NOT NULL,
    avatar_url character varying(2000),
    sales_policy character varying(4000),
    address_line character varying(255),
    business_name character varying(255),
    city character varying(255),
    contact_name character varying(255),
    country character varying(255),
    district character varying(255),
    phone character varying(255),
    tax_code character varying(255),
    ward character varying(255),
    customer_status character varying(64) NOT NULL,
    suspended_at timestamp without time zone
);


ALTER TABLE public.dealers OWNER TO fourthitek_user;

--
-- Name: email_verification_tokens; Type: TABLE; Schema: public; Owner: fourthitek_user
--

CREATE TABLE public.email_verification_tokens (
    account_id bigint NOT NULL,
    created_at timestamp(6) with time zone,
    expires_at timestamp(6) with time zone NOT NULL,
    used_at timestamp(6) with time zone,
    id bigint NOT NULL,
    token_hash character varying(64) NOT NULL
);


ALTER TABLE public.email_verification_tokens OWNER TO fourthitek_user;

--
-- Name: email_verification_tokens_id_seq; Type: SEQUENCE; Schema: public; Owner: fourthitek_user
--

ALTER TABLE public.email_verification_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.email_verification_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: financial_settlements; Type: TABLE; Schema: public; Owner: fourthitek_user
--

CREATE TABLE public.financial_settlements (
    id bigint NOT NULL,
    order_id bigint NOT NULL,
    type character varying(64) NOT NULL,
    amount numeric(19,2) NOT NULL,
    status character varying(32) DEFAULT 'PENDING'::character varying NOT NULL,
    created_by character varying(255),
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    resolution text,
    resolved_by character varying(255),
    resolved_at timestamp without time zone
);


ALTER TABLE public.financial_settlements OWNER TO fourthitek_user;

--
-- Name: financial_settlements_id_seq; Type: SEQUENCE; Schema: public; Owner: fourthitek_user
--

CREATE SEQUENCE public.financial_settlements_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.financial_settlements_id_seq OWNER TO fourthitek_user;

--
-- Name: financial_settlements_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fourthitek_user
--

ALTER SEQUENCE public.financial_settlements_id_seq OWNED BY public.financial_settlements.id;


--
-- Name: flyway_schema_history; Type: TABLE; Schema: public; Owner: fourthitek_user
--

CREATE TABLE public.flyway_schema_history (
    installed_rank integer NOT NULL,
    version character varying(50),
    description character varying(200) NOT NULL,
    type character varying(20) NOT NULL,
    script character varying(1000) NOT NULL,
    checksum integer,
    installed_by character varying(100) NOT NULL,
    installed_on timestamp without time zone DEFAULT now() NOT NULL,
    execution_time integer NOT NULL,
    success boolean NOT NULL
);


ALTER TABLE public.flyway_schema_history OWNER TO fourthitek_user;

--
-- Name: notifies; Type: TABLE; Schema: public; Owner: fourthitek_user
--

CREATE TABLE public.notifies (
    is_read boolean,
    created_at timestamp(6) with time zone,
    id bigint NOT NULL,
    id_account bigint,
    read_at timestamp(6) with time zone,
    content text,
    link character varying(255),
    title character varying(255),
    type character varying(64),
    deep_link character varying(255)
);


ALTER TABLE public.notifies OWNER TO fourthitek_user;

--
-- Name: notifies_id_seq; Type: SEQUENCE; Schema: public; Owner: fourthitek_user
--

ALTER TABLE public.notifies ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notifies_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: order_adjustments; Type: TABLE; Schema: public; Owner: fourthitek_user
--

CREATE TABLE public.order_adjustments (
    id bigint NOT NULL,
    order_id bigint NOT NULL,
    type character varying(32) NOT NULL,
    amount numeric(19,2) NOT NULL,
    reason text NOT NULL,
    reference_code character varying(255),
    created_by character varying(255) NOT NULL,
    created_by_role character varying(64),
    created_at timestamp without time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.order_adjustments OWNER TO fourthitek_user;

--
-- Name: order_adjustments_id_seq; Type: SEQUENCE; Schema: public; Owner: fourthitek_user
--

CREATE SEQUENCE public.order_adjustments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.order_adjustments_id_seq OWNER TO fourthitek_user;

--
-- Name: order_adjustments_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fourthitek_user
--

ALTER SEQUENCE public.order_adjustments_id_seq OWNED BY public.order_adjustments.id;


--
-- Name: order_items; Type: TABLE; Schema: public; Owner: fourthitek_user
--

CREATE TABLE public.order_items (
    quantity integer,
    unit_price numeric(38,2),
    id bigint NOT NULL,
    id_order bigint,
    id_product bigint,
    product_name_snapshot character varying(255),
    product_sku_snapshot character varying(255)
);


ALTER TABLE public.order_items OWNER TO fourthitek_user;

--
-- Name: order_items_id_seq; Type: SEQUENCE; Schema: public; Owner: fourthitek_user
--

ALTER TABLE public.order_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.order_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: orders; Type: TABLE; Schema: public; Owner: fourthitek_user
--

CREATE TABLE public.orders (
    is_deleted boolean,
    paid_amount numeric(38,2),
    shipping_fee integer,
    created_at timestamp(6) with time zone,
    id bigint NOT NULL,
    id_dealer bigint,
    updated_at timestamp(6) with time zone,
    note text,
    order_code character varying(255),
    receiver_address character varying(255),
    receiver_name character varying(255),
    receiver_phone character varying(255),
    payment_method character varying(64),
    payment_status character varying(64),
    status character varying(64),
    completed_at timestamp with time zone,
    financial_settlement_required boolean DEFAULT false,
    stale_review_required boolean DEFAULT false,
    idempotency_key character varying(128),
    version bigint DEFAULT 0 NOT NULL,
    confirmed_at timestamp with time zone,
    subtotal_amount numeric(38,2),
    discount_percent integer,
    discount_amount numeric(38,2),
    applied_discount_rule_id bigint,
    applied_discount_rule_label character varying(255),
    vat_percent integer,
    vat_amount numeric(38,2),
    total_amount numeric(38,2)
);


ALTER TABLE public.orders OWNER TO fourthitek_user;

--
-- Name: orders_id_seq; Type: SEQUENCE; Schema: public; Owner: fourthitek_user
--

ALTER TABLE public.orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: password_reset_tokens; Type: TABLE; Schema: public; Owner: fourthitek_user
--

CREATE TABLE public.password_reset_tokens (
    account_id bigint NOT NULL,
    created_at timestamp(6) with time zone,
    expires_at timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL,
    token character varying(120) NOT NULL
);


ALTER TABLE public.password_reset_tokens OWNER TO fourthitek_user;

--
-- Name: password_reset_tokens_id_seq; Type: SEQUENCE; Schema: public; Owner: fourthitek_user
--

ALTER TABLE public.password_reset_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.password_reset_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: payments; Type: TABLE; Schema: public; Owner: fourthitek_user
--

CREATE TABLE public.payments (
    amount numeric(38,2),
    created_at timestamp(6) with time zone,
    id bigint NOT NULL,
    id_order bigint,
    paid_at timestamp(6) with time zone,
    channel character varying(255),
    note text,
    proof_file_name character varying(255),
    transaction_code character varying(255),
    method character varying(64),
    status character varying(64),
    reviewed boolean DEFAULT false NOT NULL
);


ALTER TABLE public.payments OWNER TO fourthitek_user;

--
-- Name: payments_id_seq; Type: SEQUENCE; Schema: public; Owner: fourthitek_user
--

ALTER TABLE public.payments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: product_of_carts; Type: TABLE; Schema: public; Owner: fourthitek_user
--

CREATE TABLE public.product_of_carts (
    price_snapshot numeric(38,2),
    id bigint NOT NULL,
    id_product bigint,
    note character varying(255)
);


ALTER TABLE public.product_of_carts OWNER TO fourthitek_user;

--
-- Name: product_of_carts_id_seq; Type: SEQUENCE; Schema: public; Owner: fourthitek_user
--

ALTER TABLE public.product_of_carts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.product_of_carts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: product_serials; Type: TABLE; Schema: public; Owner: fourthitek_user
--

CREATE TABLE public.product_serials (
    id bigint NOT NULL,
    id_dealer bigint,
    id_order bigint,
    id_product bigint,
    imported_at timestamp(6) with time zone,
    serial character varying(255),
    warehouse_id character varying(255),
    warehouse_name character varying(255),
    status character varying(64)
);


ALTER TABLE public.product_serials OWNER TO fourthitek_user;

--
-- Name: product_serials_id_seq; Type: SEQUENCE; Schema: public; Owner: fourthitek_user
--

ALTER TABLE public.product_serials ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.product_serials_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: products; Type: TABLE; Schema: public; Owner: fourthitek_user
--

CREATE TABLE public.products (
    is_deleted boolean,
    is_featured boolean,
    retail_price numeric(38,2),
    show_on_homepage boolean,
    stock integer,
    warranty_period integer,
    created_at timestamp(6) with time zone,
    id bigint NOT NULL,
    updated_at timestamp(6) with time zone,
    name text,
    short_description text,
    sku character varying(255),
    descriptions jsonb,
    image jsonb,
    publish_status character varying(64),
    specifications jsonb,
    videos jsonb
);


ALTER TABLE public.products OWNER TO fourthitek_user;

--
-- Name: products_id_seq; Type: SEQUENCE; Schema: public; Owner: fourthitek_user
--

ALTER TABLE public.products ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: public_content_entries; Type: TABLE; Schema: public; Owner: fourthitek_user
--

CREATE TABLE public.public_content_entries (
    id bigint NOT NULL,
    content_key character varying(120) NOT NULL,
    locale character varying(8) NOT NULL,
    payload text NOT NULL,
    published boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone,
    updated_at timestamp with time zone
);


ALTER TABLE public.public_content_entries OWNER TO fourthitek_user;

--
-- Name: public_content_entries_id_seq; Type: SEQUENCE; Schema: public; Owner: fourthitek_user
--

ALTER TABLE public.public_content_entries ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.public_content_entries_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: push_device_tokens; Type: TABLE; Schema: public; Owner: fourthitek_user
--

CREATE TABLE public.push_device_tokens (
    id bigint NOT NULL,
    account_id bigint NOT NULL,
    token character varying(512) NOT NULL,
    platform character varying(32) NOT NULL,
    device_name character varying(120),
    app_version character varying(40),
    language_code character varying(12),
    is_active boolean DEFAULT true NOT NULL,
    last_seen_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


ALTER TABLE public.push_device_tokens OWNER TO fourthitek_user;

--
-- Name: push_device_tokens_id_seq; Type: SEQUENCE; Schema: public; Owner: fourthitek_user
--

CREATE SEQUENCE public.push_device_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.push_device_tokens_id_seq OWNER TO fourthitek_user;

--
-- Name: push_device_tokens_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fourthitek_user
--

ALTER SEQUENCE public.push_device_tokens_id_seq OWNED BY public.push_device_tokens.id;


--
-- Name: refresh_token_sessions; Type: TABLE; Schema: public; Owner: fourthitek_user
--

CREATE TABLE public.refresh_token_sessions (
    id bigint NOT NULL,
    account_id bigint NOT NULL,
    token_id character varying(64) NOT NULL,
    expires_at timestamp without time zone NOT NULL,
    revoked_at timestamp without time zone,
    replaced_by_token_id character varying(64),
    created_at timestamp without time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.refresh_token_sessions OWNER TO fourthitek_user;

--
-- Name: refresh_token_sessions_id_seq; Type: SEQUENCE; Schema: public; Owner: fourthitek_user
--

CREATE SEQUENCE public.refresh_token_sessions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.refresh_token_sessions_id_seq OWNER TO fourthitek_user;

--
-- Name: refresh_token_sessions_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fourthitek_user
--

ALTER SEQUENCE public.refresh_token_sessions_id_seq OWNED BY public.refresh_token_sessions.id;


--
-- Name: return_request_attachments; Type: TABLE; Schema: public; Owner: fourthitek_user
--

CREATE TABLE public.return_request_attachments (
    id bigint NOT NULL,
    request_id bigint NOT NULL,
    request_item_id bigint,
    url character varying(2048) NOT NULL,
    file_name character varying(255),
    category character varying(64) NOT NULL
);


ALTER TABLE public.return_request_attachments OWNER TO fourthitek_user;

--
-- Name: return_request_attachments_id_seq; Type: SEQUENCE; Schema: public; Owner: fourthitek_user
--

ALTER TABLE public.return_request_attachments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.return_request_attachments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: return_request_events; Type: TABLE; Schema: public; Owner: fourthitek_user
--

CREATE TABLE public.return_request_events (
    id bigint NOT NULL,
    request_id bigint NOT NULL,
    event_type character varying(128) NOT NULL,
    actor character varying(255),
    actor_role character varying(64),
    payload_json text,
    created_at timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


ALTER TABLE public.return_request_events OWNER TO fourthitek_user;

--
-- Name: return_request_events_id_seq; Type: SEQUENCE; Schema: public; Owner: fourthitek_user
--

ALTER TABLE public.return_request_events ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.return_request_events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: return_request_items; Type: TABLE; Schema: public; Owner: fourthitek_user
--

CREATE TABLE public.return_request_items (
    id bigint NOT NULL,
    request_id bigint NOT NULL,
    order_item_id bigint,
    product_id bigint NOT NULL,
    product_serial_id bigint NOT NULL,
    serial_snapshot character varying(255) NOT NULL,
    item_status character varying(64) NOT NULL,
    condition_on_request character varying(64),
    admin_decision_note text,
    inspection_note text,
    final_resolution character varying(64),
    replacement_order_id bigint,
    refund_amount numeric(19,2),
    credit_amount numeric(19,2),
    order_adjustment_id bigint
);


ALTER TABLE public.return_request_items OWNER TO fourthitek_user;

--
-- Name: return_request_items_id_seq; Type: SEQUENCE; Schema: public; Owner: fourthitek_user
--

ALTER TABLE public.return_request_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.return_request_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: return_requests; Type: TABLE; Schema: public; Owner: fourthitek_user
--

CREATE TABLE public.return_requests (
    id bigint NOT NULL,
    request_code character varying(64) NOT NULL,
    dealer_id bigint NOT NULL,
    order_id bigint NOT NULL,
    type character varying(64) NOT NULL,
    status character varying(64) NOT NULL,
    requested_resolution character varying(64) NOT NULL,
    reason_code character varying(128),
    reason_detail text,
    support_ticket_id bigint,
    requested_at timestamp(6) with time zone,
    reviewed_at timestamp(6) with time zone,
    received_at timestamp(6) with time zone,
    completed_at timestamp(6) with time zone,
    created_by character varying(255),
    updated_by character varying(255),
    created_at timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


ALTER TABLE public.return_requests OWNER TO fourthitek_user;

--
-- Name: return_requests_id_seq; Type: SEQUENCE; Schema: public; Owner: fourthitek_user
--

ALTER TABLE public.return_requests ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.return_requests_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: roles; Type: TABLE; Schema: public; Owner: fourthitek_user
--

CREATE TABLE public.roles (
    id bigint NOT NULL,
    description character varying(255),
    name character varying(255)
);


ALTER TABLE public.roles OWNER TO fourthitek_user;

--
-- Name: roles_id_seq; Type: SEQUENCE; Schema: public; Owner: fourthitek_user
--

ALTER TABLE public.roles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.roles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: support_ticket_messages; Type: TABLE; Schema: public; Owner: fourthitek_user
--

CREATE TABLE public.support_ticket_messages (
    id bigint NOT NULL,
    ticket_id bigint NOT NULL,
    author_role character varying(32) NOT NULL,
    author_name character varying(255),
    internal_note boolean DEFAULT false NOT NULL,
    message text NOT NULL,
    created_at timestamp(6) with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    attachments text
);


ALTER TABLE public.support_ticket_messages OWNER TO fourthitek_user;

--
-- Name: support_ticket_messages_id_seq; Type: SEQUENCE; Schema: public; Owner: fourthitek_user
--

ALTER TABLE public.support_ticket_messages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.support_ticket_messages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: media_assets; Type: TABLE; Schema: public; Owner: fourthitek_user
--

CREATE TABLE public.media_assets (
    id bigint NOT NULL,
    object_key character varying(1024) NOT NULL,
    original_file_name character varying(512) NOT NULL,
    stored_file_name character varying(512),
    content_type character varying(255) NOT NULL,
    media_type character varying(32) NOT NULL,
    category character varying(64) NOT NULL,
    size_bytes bigint NOT NULL,
    storage_provider character varying(32) NOT NULL,
    owner_account_id bigint,
    uploaded_by_account_id bigint,
    status character varying(32) NOT NULL,
    linked_entity_type character varying(128),
    linked_entity_id bigint,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    finalized_at timestamp without time zone,
    deleted_at timestamp without time zone
);


ALTER TABLE public.media_assets OWNER TO fourthitek_user;

--
-- Name: media_assets_id_seq; Type: SEQUENCE; Schema: public; Owner: fourthitek_user
--

ALTER TABLE public.media_assets ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.media_assets_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: support_ticket_message_attachments; Type: TABLE; Schema: public; Owner: fourthitek_user
--

CREATE TABLE public.support_ticket_message_attachments (
    message_id bigint NOT NULL,
    media_asset_id bigint NOT NULL,
    sort_order integer NOT NULL
);


ALTER TABLE public.support_ticket_message_attachments OWNER TO fourthitek_user;

--
-- Name: support_ticket_message_attachments support_ticket_message_attachments_pkey; Type: CONSTRAINT; Schema: public; Owner: fourthitek_user
--

ALTER TABLE ONLY public.support_ticket_message_attachments
    ADD CONSTRAINT support_ticket_message_attachments_pkey PRIMARY KEY (message_id, media_asset_id);


--
-- Name: media_assets media_assets_object_key_key; Type: CONSTRAINT; Schema: public; Owner: fourthitek_user
--

ALTER TABLE ONLY public.media_assets
    ADD CONSTRAINT media_assets_object_key_key UNIQUE (object_key);


--
-- Name: media_assets media_assets_pkey; Type: CONSTRAINT; Schema: public; Owner: fourthitek_user
--

ALTER TABLE ONLY public.media_assets
    ADD CONSTRAINT media_assets_pkey PRIMARY KEY (id);


--
-- Name: unmatched_payments; Type: TABLE; Schema: public; Owner: fourthitek_user
--

CREATE TABLE public.unmatched_payments (
    id bigint NOT NULL,
    transaction_code character varying(512),
    amount numeric(19,2) NOT NULL,
    sender_info text,
    content text,
    order_code_hint character varying(128),
    received_at timestamp without time zone,
    reason character varying(64) NOT NULL,
    status character varying(32) DEFAULT 'PENDING'::character varying NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    resolution text,
    resolved_by character varying(255),
    resolved_at timestamp without time zone,
    matched_order_id bigint
);


ALTER TABLE public.unmatched_payments OWNER TO fourthitek_user;

--
-- Name: unmatched_payments_id_seq; Type: SEQUENCE; Schema: public; Owner: fourthitek_user
--

CREATE SEQUENCE public.unmatched_payments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.unmatched_payments_id_seq OWNER TO fourthitek_user;

--
-- Name: unmatched_payments_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: fourthitek_user
--

ALTER SEQUENCE public.unmatched_payments_id_seq OWNED BY public.unmatched_payments.id;


--
-- Name: warranties; Type: TABLE; Schema: public; Owner: fourthitek_user
--

CREATE TABLE public.warranties (
    created_at timestamp(6) with time zone,
    id bigint NOT NULL,
    id_dealer bigint,
    id_order bigint,
    id_product_serial bigint,
    updated_at timestamp(6) with time zone,
    warranty_end timestamp(6) with time zone,
    warranty_start timestamp(6) with time zone,
    customer_address character varying(255),
    customer_email character varying(255),
    customer_name character varying(255),
    customer_phone character varying(255),
    warranty_code character varying(255),
    status character varying(64),
    purchase_date date
);


ALTER TABLE public.warranties OWNER TO fourthitek_user;

--
-- Name: warranties_id_seq; Type: SEQUENCE; Schema: public; Owner: fourthitek_user
--

ALTER TABLE public.warranties ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.warranties_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: financial_settlements id; Type: DEFAULT; Schema: public; Owner: fourthitek_user
--

ALTER TABLE ONLY public.financial_settlements ALTER COLUMN id SET DEFAULT nextval('public.financial_settlements_id_seq'::regclass);


--
-- Name: order_adjustments id; Type: DEFAULT; Schema: public; Owner: fourthitek_user
--

ALTER TABLE ONLY public.order_adjustments ALTER COLUMN id SET DEFAULT nextval('public.order_adjustments_id_seq'::regclass);


--
-- Name: push_device_tokens id; Type: DEFAULT; Schema: public; Owner: fourthitek_user
--

ALTER TABLE ONLY public.push_device_tokens ALTER COLUMN id SET DEFAULT nextval('public.push_device_tokens_id_seq'::regclass);


--
-- Name: refresh_token_sessions id; Type: DEFAULT; Schema: public; Owner: fourthitek_user
--

ALTER TABLE ONLY public.refresh_token_sessions ALTER COLUMN id SET DEFAULT nextval('public.refresh_token_sessions_id_seq'::regclass);


--
-- Name: unmatched_payments id; Type: DEFAULT; Schema: public; Owner: fourthitek_user
--

ALTER TABLE ONLY public.unmatched_payments ALTER COLUMN id SET DEFAULT nextval('public.unmatched_payments_id_seq'::regclass);


--
-- Name: account_roles account_roles_pkey; Type: CONSTRAINT; Schema: public; Owner: fourthitek_user
--

ALTER TABLE ONLY public.account_roles
    ADD CONSTRAINT account_roles_pkey PRIMARY KEY (account_id, role_id);


--
-- Name: accounts accounts_email_key; Type: CONSTRAINT; Schema: public; Owner: fourthitek_user
--

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT accounts_email_key UNIQUE (email);


--
-- Name: accounts accounts_pkey; Type: CONSTRAINT; Schema: public; Owner: fourthitek_user
--

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT accounts_pkey PRIMARY KEY (id);


--
-- Name: accounts accounts_username_key; Type: CONSTRAINT; Schema: public; Owner: fourthitek_user
--

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT accounts_username_key UNIQUE (username);


--
-- Name: admin_settings admin_settings_pkey; Type: CONSTRAINT; Schema: public; Owner: fourthitek_user
--

ALTER TABLE ONLY public.admin_settings
    ADD CONSTRAINT admin_settings_pkey PRIMARY KEY (id);


--
-- Name: admins admins_pkey; Type: CONSTRAINT; Schema: public; Owner: fourthitek_user
--

ALTER TABLE ONLY public.admins
    ADD CONSTRAINT admins_pkey PRIMARY KEY (id_account);


--
-- Name: audit_logs audit_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: fourthitek_user
--

ALTER TABLE ONLY public.audit_logs
    ADD CONSTRAINT audit_logs_pkey PRIMARY KEY (id);


--
-- Name: blogs blogs_pkey; Type: CONSTRAINT; Schema: public; Owner: fourthitek_user
--

ALTER TABLE ONLY public.blogs
    ADD CONSTRAINT blogs_pkey PRIMARY KEY (id);


--
-- Name: bulk_discounts bulk_discounts_pkey; Type: CONSTRAINT; Schema: public; Owner: fourthitek_user
--

ALTER TABLE ONLY public.bulk_discounts
    ADD CONSTRAINT bulk_discounts_pkey PRIMARY KEY (id);


--
-- Name: category_blogs category_blogs_pkey; Type: CONSTRAINT; Schema: public; Owner: fourthitek_user
--

ALTER TABLE ONLY public.category_blogs
    ADD CONSTRAINT category_blogs_pkey PRIMARY KEY (id);


--
-- Name: customers customers_phone_key; Type: CONSTRAINT; Schema: public; Owner: fourthitek_user
--

ALTER TABLE ONLY public.customers
    ADD CONSTRAINT customers_phone_key UNIQUE (phone);


--
-- Name: customers customers_pkey; Type: CONSTRAINT; Schema: public; Owner: fourthitek_user
--

ALTER TABLE ONLY public.customers
    ADD CONSTRAINT customers_pkey PRIMARY KEY (id_account);


--
-- Name: dealer_cart_items dealer_cart_items_pkey; Type: CONSTRAINT; Schema: public; Owner: fourthitek_user
--

ALTER TABLE ONLY public.dealer_cart_items
    ADD CONSTRAINT dealer_cart_items_pkey PRIMARY KEY (id_dealer, id_product_of_cart);


--
-- Name: dealer_support_tickets dealer_support_tickets_pkey; Type: CONSTRAINT; Schema: public; Owner: fourthitek_user
--

ALTER TABLE ONLY public.dealer_support_tickets
    ADD CONSTRAINT dealer_support_tickets_pkey PRIMARY KEY (id);


--
-- Name: dealer_support_tickets dealer_support_tickets_ticket_code_key; Type: CONSTRAINT; Schema: public; Owner: fourthitek_user
--

ALTER TABLE ONLY public.dealer_support_tickets
    ADD CONSTRAINT dealer_support_tickets_ticket_code_key UNIQUE (ticket_code);


--
-- Name: dealers dealers_phone_key; Type: CONSTRAINT; Schema: public; Owner: fourthitek_user
--

ALTER TABLE ONLY public.dealers
    ADD CONSTRAINT dealers_phone_key UNIQUE (phone);


--
-- Name: dealers dealers_pkey; Type: CONSTRAINT; Schema: public; Owner: fourthitek_user
--

ALTER TABLE ONLY public.dealers
    ADD CONSTRAINT dealers_pkey PRIMARY KEY (id_account);


--
-- Name: dealers dealers_tax_code_key; Type: CONSTRAINT; Schema: public; Owner: fourthitek_user
--

ALTER TABLE ONLY public.dealers
    ADD CONSTRAINT dealers_tax_code_key UNIQUE (tax_code);


--
-- Name: email_verification_tokens email_verification_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: fourthitek_user
--

ALTER TABLE ONLY public.email_verification_tokens
    ADD CONSTRAINT email_verification_tokens_pkey PRIMARY KEY (id);


--
-- Name: email_verification_tokens email_verification_tokens_token_hash_key; Type: CONSTRAINT; Schema: public; Owner: fourthitek_user
--

ALTER TABLE ONLY public.email_verification_tokens
    ADD CONSTRAINT email_verification_tokens_token_hash_key UNIQUE (token_hash);


--
-- Name: financial_settlements financial_settlements_pkey; Type: CONSTRAINT; Schema: public; Owner: fourthitek_user
--

ALTER TABLE ONLY public.financial_settlements
    ADD CONSTRAINT financial_settlements_pkey PRIMARY KEY (id);


--
-- Name: flyway_schema_history flyway_schema_history_pk; Type: CONSTRAINT; Schema: public; Owner: fourthitek_user
--

ALTER TABLE ONLY public.flyway_schema_history
    ADD CONSTRAINT flyway_schema_history_pk PRIMARY KEY (installed_rank);


--
-- Name: notifies notifies_pkey; Type: CONSTRAINT; Schema: public; Owner: fourthitek_user
--

ALTER TABLE ONLY public.notifies
    ADD CONSTRAINT notifies_pkey PRIMARY KEY (id);


--
-- Name: order_adjustments order_adjustments_pkey; Type: CONSTRAINT; Schema: public; Owner: fourthitek_user
--

ALTER TABLE ONLY public.order_adjustments
    ADD CONSTRAINT order_adjustments_pkey PRIMARY KEY (id);


--
-- Name: order_items order_items_pkey; Type: CONSTRAINT; Schema: public; Owner: fourthitek_user
--

ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT order_items_pkey PRIMARY KEY (id);


--
-- Name: orders orders_order_code_key; Type: CONSTRAINT; Schema: public; Owner: fourthitek_user
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_order_code_key UNIQUE (order_code);


--
-- Name: orders orders_pkey; Type: CONSTRAINT; Schema: public; Owner: fourthitek_user
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_pkey PRIMARY KEY (id);


--
-- Name: password_reset_tokens password_reset_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: fourthitek_user
--

ALTER TABLE ONLY public.password_reset_tokens
    ADD CONSTRAINT password_reset_tokens_pkey PRIMARY KEY (id);


--
-- Name: password_reset_tokens password_reset_tokens_token_key; Type: CONSTRAINT; Schema: public; Owner: fourthitek_user
--

ALTER TABLE ONLY public.password_reset_tokens
    ADD CONSTRAINT password_reset_tokens_token_key UNIQUE (token);


--
-- Name: payments payments_pkey; Type: CONSTRAINT; Schema: public; Owner: fourthitek_user
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT payments_pkey PRIMARY KEY (id);


--
-- Name: payments payments_transaction_code_key; Type: CONSTRAINT; Schema: public; Owner: fourthitek_user
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT payments_transaction_code_key UNIQUE (transaction_code);


--
-- Name: product_of_carts product_of_carts_pkey; Type: CONSTRAINT; Schema: public; Owner: fourthitek_user
--

ALTER TABLE ONLY public.product_of_carts
    ADD CONSTRAINT product_of_carts_pkey PRIMARY KEY (id);


--
-- Name: product_serials product_serials_pkey; Type: CONSTRAINT; Schema: public; Owner: fourthitek_user
--

ALTER TABLE ONLY public.product_serials
    ADD CONSTRAINT product_serials_pkey PRIMARY KEY (id);


--
-- Name: product_serials product_serials_serial_key; Type: CONSTRAINT; Schema: public; Owner: fourthitek_user
--

ALTER TABLE ONLY public.product_serials
    ADD CONSTRAINT product_serials_serial_key UNIQUE (serial);


--
-- Name: products products_pkey; Type: CONSTRAINT; Schema: public; Owner: fourthitek_user
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_pkey PRIMARY KEY (id);


--
-- Name: products products_sku_key; Type: CONSTRAINT; Schema: public; Owner: fourthitek_user
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_sku_key UNIQUE (sku);


--
-- Name: public_content_entries public_content_entries_pkey; Type: CONSTRAINT; Schema: public; Owner: fourthitek_user
--

ALTER TABLE ONLY public.public_content_entries
    ADD CONSTRAINT public_content_entries_pkey PRIMARY KEY (id);


--
-- Name: push_device_tokens push_device_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: fourthitek_user
--

ALTER TABLE ONLY public.push_device_tokens
    ADD CONSTRAINT push_device_tokens_pkey PRIMARY KEY (id);


--
-- Name: push_device_tokens push_device_tokens_token_key; Type: CONSTRAINT; Schema: public; Owner: fourthitek_user
--

ALTER TABLE ONLY public.push_device_tokens
    ADD CONSTRAINT push_device_tokens_token_key UNIQUE (token);


--
-- Name: refresh_token_sessions refresh_token_sessions_pkey; Type: CONSTRAINT; Schema: public; Owner: fourthitek_user
--

ALTER TABLE ONLY public.refresh_token_sessions
    ADD CONSTRAINT refresh_token_sessions_pkey PRIMARY KEY (id);


--
-- Name: refresh_token_sessions refresh_token_sessions_token_id_key; Type: CONSTRAINT; Schema: public; Owner: fourthitek_user
--

ALTER TABLE ONLY public.refresh_token_sessions
    ADD CONSTRAINT refresh_token_sessions_token_id_key UNIQUE (token_id);


--
-- Name: return_request_attachments return_request_attachments_pkey; Type: CONSTRAINT; Schema: public; Owner: fourthitek_user
--

ALTER TABLE ONLY public.return_request_attachments
    ADD CONSTRAINT return_request_attachments_pkey PRIMARY KEY (id);


--
-- Name: return_request_events return_request_events_pkey; Type: CONSTRAINT; Schema: public; Owner: fourthitek_user
--

ALTER TABLE ONLY public.return_request_events
    ADD CONSTRAINT return_request_events_pkey PRIMARY KEY (id);


--
-- Name: return_request_items return_request_items_pkey; Type: CONSTRAINT; Schema: public; Owner: fourthitek_user
--

ALTER TABLE ONLY public.return_request_items
    ADD CONSTRAINT return_request_items_pkey PRIMARY KEY (id);


--
-- Name: return_requests return_requests_pkey; Type: CONSTRAINT; Schema: public; Owner: fourthitek_user
--

ALTER TABLE ONLY public.return_requests
    ADD CONSTRAINT return_requests_pkey PRIMARY KEY (id);


--
-- Name: return_requests return_requests_request_code_key; Type: CONSTRAINT; Schema: public; Owner: fourthitek_user
--

ALTER TABLE ONLY public.return_requests
    ADD CONSTRAINT return_requests_request_code_key UNIQUE (request_code);


--
-- Name: roles roles_name_key; Type: CONSTRAINT; Schema: public; Owner: fourthitek_user
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_name_key UNIQUE (name);


--
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: public; Owner: fourthitek_user
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (id);


--
-- Name: support_ticket_messages support_ticket_messages_pkey; Type: CONSTRAINT; Schema: public; Owner: fourthitek_user
--

ALTER TABLE ONLY public.support_ticket_messages
    ADD CONSTRAINT support_ticket_messages_pkey PRIMARY KEY (id);


--
-- Name: unmatched_payments unmatched_payments_pkey; Type: CONSTRAINT; Schema: public; Owner: fourthitek_user
--

ALTER TABLE ONLY public.unmatched_payments
    ADD CONSTRAINT unmatched_payments_pkey PRIMARY KEY (id);


--
-- Name: warranties warranties_id_product_serial_key; Type: CONSTRAINT; Schema: public; Owner: fourthitek_user
--

ALTER TABLE ONLY public.warranties
    ADD CONSTRAINT warranties_id_product_serial_key UNIQUE (id_product_serial);


--
-- Name: warranties warranties_pkey; Type: CONSTRAINT; Schema: public; Owner: fourthitek_user
--

ALTER TABLE ONLY public.warranties
    ADD CONSTRAINT warranties_pkey PRIMARY KEY (id);


--
-- Name: warranties warranties_warranty_code_key; Type: CONSTRAINT; Schema: public; Owner: fourthitek_user
--

ALTER TABLE ONLY public.warranties
    ADD CONSTRAINT warranties_warranty_code_key UNIQUE (warranty_code);


--
-- Name: flyway_schema_history_s_idx; Type: INDEX; Schema: public; Owner: fourthitek_user
--

CREATE INDEX flyway_schema_history_s_idx ON public.flyway_schema_history USING btree (success);


--
-- Name: idx_audit_logs_actor; Type: INDEX; Schema: public; Owner: fourthitek_user
--

CREATE INDEX idx_audit_logs_actor ON public.audit_logs USING btree (actor);


--
-- Name: idx_audit_logs_created_at; Type: INDEX; Schema: public; Owner: fourthitek_user
--

CREATE INDEX idx_audit_logs_created_at ON public.audit_logs USING btree (created_at DESC);


--
-- Name: idx_audit_logs_entity; Type: INDEX; Schema: public; Owner: fourthitek_user
--

CREATE INDEX idx_audit_logs_entity ON public.audit_logs USING btree (entity_type, entity_id);


--
-- Name: idx_financial_settlements_order_id; Type: INDEX; Schema: public; Owner: fourthitek_user
--

CREATE INDEX idx_financial_settlements_order_id ON public.financial_settlements USING btree (order_id);


--
-- Name: idx_financial_settlements_status; Type: INDEX; Schema: public; Owner: fourthitek_user
--

CREATE INDEX idx_financial_settlements_status ON public.financial_settlements USING btree (status);


--
-- Name: idx_order_adjustments_order_id; Type: INDEX; Schema: public; Owner: fourthitek_user
--

CREATE INDEX idx_order_adjustments_order_id ON public.order_adjustments USING btree (order_id);


--
-- Name: idx_orders_status_confirmed_at; Type: INDEX; Schema: public; Owner: fourthitek_user
--

CREATE INDEX idx_orders_status_confirmed_at ON public.orders USING btree (status, confirmed_at);


--
-- Name: idx_ps_dealer_order_imported; Type: INDEX; Schema: public; Owner: fourthitek_user
--

CREATE INDEX idx_ps_dealer_order_imported ON public.product_serials USING btree (id_dealer, id_order, imported_at DESC);


--
-- Name: idx_ps_product_dealer_status; Type: INDEX; Schema: public; Owner: fourthitek_user
--

CREATE INDEX idx_ps_product_dealer_status ON public.product_serials USING btree (id_product, id_dealer, status);


--
-- Name: idx_push_device_tokens_account_active; Type: INDEX; Schema: public; Owner: fourthitek_user
--

CREATE INDEX idx_push_device_tokens_account_active ON public.push_device_tokens USING btree (account_id, is_active);


--
-- Name: idx_refresh_token_sessions_account_id; Type: INDEX; Schema: public; Owner: fourthitek_user
--

CREATE INDEX idx_refresh_token_sessions_account_id ON public.refresh_token_sessions USING btree (account_id);


--
-- Name: idx_refresh_token_sessions_expires_at; Type: INDEX; Schema: public; Owner: fourthitek_user
--

CREATE INDEX idx_refresh_token_sessions_expires_at ON public.refresh_token_sessions USING btree (expires_at);


--
-- Name: idx_return_request_attachments_item_id; Type: INDEX; Schema: public; Owner: fourthitek_user
--

CREATE INDEX idx_return_request_attachments_item_id ON public.return_request_attachments USING btree (request_item_id);


--
-- Name: idx_return_request_attachments_request_id; Type: INDEX; Schema: public; Owner: fourthitek_user
--

CREATE INDEX idx_return_request_attachments_request_id ON public.return_request_attachments USING btree (request_id);


--
-- Name: idx_return_request_events_request_created_at; Type: INDEX; Schema: public; Owner: fourthitek_user
--

CREATE INDEX idx_return_request_events_request_created_at ON public.return_request_events USING btree (request_id, created_at);


--
-- Name: idx_return_request_items_order_adjustment_id; Type: INDEX; Schema: public; Owner: fourthitek_user
--

CREATE INDEX idx_return_request_items_order_adjustment_id ON public.return_request_items USING btree (order_adjustment_id);


--
-- Name: idx_return_request_items_request_id; Type: INDEX; Schema: public; Owner: fourthitek_user
--

CREATE INDEX idx_return_request_items_request_id ON public.return_request_items USING btree (request_id);


--
-- Name: idx_return_request_items_serial_id; Type: INDEX; Schema: public; Owner: fourthitek_user
--

CREATE INDEX idx_return_request_items_serial_id ON public.return_request_items USING btree (product_serial_id);


--
-- Name: idx_return_request_items_serial_request; Type: INDEX; Schema: public; Owner: fourthitek_user
--

CREATE INDEX idx_return_request_items_serial_request ON public.return_request_items USING btree (product_serial_id, request_id);


--
-- Name: idx_return_request_items_status; Type: INDEX; Schema: public; Owner: fourthitek_user
--

CREATE INDEX idx_return_request_items_status ON public.return_request_items USING btree (item_status);


--
-- Name: idx_return_requests_dealer_created_at; Type: INDEX; Schema: public; Owner: fourthitek_user
--

CREATE INDEX idx_return_requests_dealer_created_at ON public.return_requests USING btree (dealer_id, created_at DESC);


--
-- Name: idx_return_requests_dealer_status_created_at; Type: INDEX; Schema: public; Owner: fourthitek_user
--

CREATE INDEX idx_return_requests_dealer_status_created_at ON public.return_requests USING btree (dealer_id, status, created_at DESC);


--
-- Name: idx_return_requests_order_id; Type: INDEX; Schema: public; Owner: fourthitek_user
--

CREATE INDEX idx_return_requests_order_id ON public.return_requests USING btree (order_id);


--
-- Name: idx_return_requests_status; Type: INDEX; Schema: public; Owner: fourthitek_user
--

CREATE INDEX idx_return_requests_status ON public.return_requests USING btree (status);


--
-- Name: idx_return_requests_status_created_at; Type: INDEX; Schema: public; Owner: fourthitek_user
--

CREATE INDEX idx_return_requests_status_created_at ON public.return_requests USING btree (status, created_at DESC);


--
-- Name: idx_return_requests_support_ticket_id; Type: INDEX; Schema: public; Owner: fourthitek_user
--

CREATE INDEX idx_return_requests_support_ticket_id ON public.return_requests USING btree (support_ticket_id);


--
-- Name: idx_support_ticket_messages_ticket_created_at; Type: INDEX; Schema: public; Owner: fourthitek_user
--

CREATE INDEX idx_support_ticket_messages_ticket_created_at ON public.support_ticket_messages USING btree (ticket_id, created_at);


--
-- Name: idx_media_assets_category_status; Type: INDEX; Schema: public; Owner: fourthitek_user
--

CREATE INDEX idx_media_assets_category_status ON public.media_assets USING btree (category, status);


--
-- Name: idx_media_assets_linked_entity; Type: INDEX; Schema: public; Owner: fourthitek_user
--

CREATE INDEX idx_media_assets_linked_entity ON public.media_assets USING btree (linked_entity_type, linked_entity_id);


--
-- Name: idx_media_assets_media_type; Type: INDEX; Schema: public; Owner: fourthitek_user
--

CREATE INDEX idx_media_assets_media_type ON public.media_assets USING btree (media_type);


--
-- Name: idx_media_assets_owner; Type: INDEX; Schema: public; Owner: fourthitek_user
--

CREATE INDEX idx_media_assets_owner ON public.media_assets USING btree (owner_account_id);


--
-- Name: idx_media_assets_status_created_at; Type: INDEX; Schema: public; Owner: fourthitek_user
--

CREATE INDEX idx_media_assets_status_created_at ON public.media_assets USING btree (status, created_at);


--
-- Name: idx_media_assets_status_deleted_at; Type: INDEX; Schema: public; Owner: fourthitek_user
--

CREATE INDEX idx_media_assets_status_deleted_at ON public.media_assets USING btree (status, deleted_at);


--
-- Name: idx_media_assets_uploaded_by; Type: INDEX; Schema: public; Owner: fourthitek_user
--

CREATE INDEX idx_media_assets_uploaded_by ON public.media_assets USING btree (uploaded_by_account_id);


--
-- Name: idx_support_message_attachments_message_sort; Type: INDEX; Schema: public; Owner: fourthitek_user
--

CREATE INDEX idx_support_message_attachments_message_sort ON public.support_ticket_message_attachments USING btree (message_id, sort_order);


--
-- Name: idx_unmatched_payments_reason; Type: INDEX; Schema: public; Owner: fourthitek_user
--

CREATE INDEX idx_unmatched_payments_reason ON public.unmatched_payments USING btree (reason);


--
-- Name: idx_unmatched_payments_status; Type: INDEX; Schema: public; Owner: fourthitek_user
--

CREATE INDEX idx_unmatched_payments_status ON public.unmatched_payments USING btree (status);


--
-- Name: uk_orders_dealer_idempotency_key; Type: INDEX; Schema: public; Owner: fourthitek_user
--

CREATE UNIQUE INDEX uk_orders_dealer_idempotency_key ON public.orders USING btree (id_dealer, idempotency_key);


--
-- Name: uk_public_content_entries_key_locale; Type: INDEX; Schema: public; Owner: fourthitek_user
--

CREATE UNIQUE INDEX uk_public_content_entries_key_locale ON public.public_content_entries USING btree (content_key, locale);


--
-- Name: financial_settlements financial_settlements_order_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: fourthitek_user
--

ALTER TABLE ONLY public.financial_settlements
    ADD CONSTRAINT financial_settlements_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id);


--
-- Name: order_items fk2eoo5mp3khsag7l93o41u1w7g; Type: FK CONSTRAINT; Schema: public; Owner: fourthitek_user
--

ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT fk2eoo5mp3khsag7l93o41u1w7g FOREIGN KEY (id_product) REFERENCES public.products(id);


--
-- Name: notifies fk5dfs09khy4wndix9379tuakkc; Type: FK CONSTRAINT; Schema: public; Owner: fourthitek_user
--

ALTER TABLE ONLY public.notifies
    ADD CONSTRAINT fk5dfs09khy4wndix9379tuakkc FOREIGN KEY (id_account) REFERENCES public.accounts(id);


--
-- Name: blogs fk5mfonahgvvoup1qgxx1j98ju1; Type: FK CONSTRAINT; Schema: public; Owner: fourthitek_user
--

ALTER TABLE ONLY public.blogs
    ADD CONSTRAINT fk5mfonahgvvoup1qgxx1j98ju1 FOREIGN KEY (id_category_blog) REFERENCES public.category_blogs(id);


--
-- Name: account_roles fk61h48dsir3h82pxbq3cwgp0ce; Type: FK CONSTRAINT; Schema: public; Owner: fourthitek_user
--

ALTER TABLE ONLY public.account_roles
    ADD CONSTRAINT fk61h48dsir3h82pxbq3cwgp0ce FOREIGN KEY (account_id) REFERENCES public.accounts(id);


--
-- Name: account_roles fk6r8nxkn3hctohyllteivfr5hy; Type: FK CONSTRAINT; Schema: public; Owner: fourthitek_user
--

ALTER TABLE ONLY public.account_roles
    ADD CONSTRAINT fk6r8nxkn3hctohyllteivfr5hy FOREIGN KEY (role_id) REFERENCES public.roles(id);


--
-- Name: product_serials fk7wyatm1g479dj1vy0kyn4hg4g; Type: FK CONSTRAINT; Schema: public; Owner: fourthitek_user
--

ALTER TABLE ONLY public.product_serials
    ADD CONSTRAINT fk7wyatm1g479dj1vy0kyn4hg4g FOREIGN KEY (id_dealer) REFERENCES public.dealers(id_account);


--
-- Name: product_of_carts fk9c5f52pydjkmo5uxb37fxk74j; Type: FK CONSTRAINT; Schema: public; Owner: fourthitek_user
--

ALTER TABLE ONLY public.product_of_carts
    ADD CONSTRAINT fk9c5f52pydjkmo5uxb37fxk74j FOREIGN KEY (id_product) REFERENCES public.products(id);


--
-- Name: dealer_support_tickets fk_dealer_support_tickets_assignee; Type: FK CONSTRAINT; Schema: public; Owner: fourthitek_user
--

ALTER TABLE ONLY public.dealer_support_tickets
    ADD CONSTRAINT fk_dealer_support_tickets_assignee FOREIGN KEY (assignee_id) REFERENCES public.admins(id_account);


--
-- Name: email_verification_tokens fk_email_verification_tokens_account; Type: FK CONSTRAINT; Schema: public; Owner: fourthitek_user
--

ALTER TABLE ONLY public.email_verification_tokens
    ADD CONSTRAINT fk_email_verification_tokens_account FOREIGN KEY (account_id) REFERENCES public.accounts(id);


--
-- Name: return_request_attachments fk_return_request_attachments_item; Type: FK CONSTRAINT; Schema: public; Owner: fourthitek_user
--

ALTER TABLE ONLY public.return_request_attachments
    ADD CONSTRAINT fk_return_request_attachments_item FOREIGN KEY (request_item_id) REFERENCES public.return_request_items(id) ON DELETE CASCADE;


--
-- Name: return_request_attachments fk_return_request_attachments_request; Type: FK CONSTRAINT; Schema: public; Owner: fourthitek_user
--

ALTER TABLE ONLY public.return_request_attachments
    ADD CONSTRAINT fk_return_request_attachments_request FOREIGN KEY (request_id) REFERENCES public.return_requests(id) ON DELETE CASCADE;


--
-- Name: return_request_events fk_return_request_events_request; Type: FK CONSTRAINT; Schema: public; Owner: fourthitek_user
--

ALTER TABLE ONLY public.return_request_events
    ADD CONSTRAINT fk_return_request_events_request FOREIGN KEY (request_id) REFERENCES public.return_requests(id) ON DELETE CASCADE;


--
-- Name: return_request_items fk_return_request_items_order_adjustment; Type: FK CONSTRAINT; Schema: public; Owner: fourthitek_user
--

ALTER TABLE ONLY public.return_request_items
    ADD CONSTRAINT fk_return_request_items_order_adjustment FOREIGN KEY (order_adjustment_id) REFERENCES public.order_adjustments(id);


--
-- Name: return_request_items fk_return_request_items_order_item; Type: FK CONSTRAINT; Schema: public; Owner: fourthitek_user
--

ALTER TABLE ONLY public.return_request_items
    ADD CONSTRAINT fk_return_request_items_order_item FOREIGN KEY (order_item_id) REFERENCES public.order_items(id);


--
-- Name: return_request_items fk_return_request_items_product; Type: FK CONSTRAINT; Schema: public; Owner: fourthitek_user
--

ALTER TABLE ONLY public.return_request_items
    ADD CONSTRAINT fk_return_request_items_product FOREIGN KEY (product_id) REFERENCES public.products(id);


--
-- Name: return_request_items fk_return_request_items_replacement_order; Type: FK CONSTRAINT; Schema: public; Owner: fourthitek_user
--

ALTER TABLE ONLY public.return_request_items
    ADD CONSTRAINT fk_return_request_items_replacement_order FOREIGN KEY (replacement_order_id) REFERENCES public.orders(id);


--
-- Name: return_request_items fk_return_request_items_request; Type: FK CONSTRAINT; Schema: public; Owner: fourthitek_user
--

ALTER TABLE ONLY public.return_request_items
    ADD CONSTRAINT fk_return_request_items_request FOREIGN KEY (request_id) REFERENCES public.return_requests(id) ON DELETE CASCADE;


--
-- Name: return_request_items fk_return_request_items_serial; Type: FK CONSTRAINT; Schema: public; Owner: fourthitek_user
--

ALTER TABLE ONLY public.return_request_items
    ADD CONSTRAINT fk_return_request_items_serial FOREIGN KEY (product_serial_id) REFERENCES public.product_serials(id);


--
-- Name: return_requests fk_return_requests_dealer; Type: FK CONSTRAINT; Schema: public; Owner: fourthitek_user
--

ALTER TABLE ONLY public.return_requests
    ADD CONSTRAINT fk_return_requests_dealer FOREIGN KEY (dealer_id) REFERENCES public.dealers(id_account);


--
-- Name: return_requests fk_return_requests_order; Type: FK CONSTRAINT; Schema: public; Owner: fourthitek_user
--

ALTER TABLE ONLY public.return_requests
    ADD CONSTRAINT fk_return_requests_order FOREIGN KEY (order_id) REFERENCES public.orders(id);


--
-- Name: return_requests fk_return_requests_support_ticket; Type: FK CONSTRAINT; Schema: public; Owner: fourthitek_user
--

ALTER TABLE ONLY public.return_requests
    ADD CONSTRAINT fk_return_requests_support_ticket FOREIGN KEY (support_ticket_id) REFERENCES public.dealer_support_tickets(id);


--
-- Name: support_ticket_messages fk_support_ticket_messages_ticket; Type: FK CONSTRAINT; Schema: public; Owner: fourthitek_user
--

ALTER TABLE ONLY public.support_ticket_messages
    ADD CONSTRAINT fk_support_ticket_messages_ticket FOREIGN KEY (ticket_id) REFERENCES public.dealer_support_tickets(id) ON DELETE CASCADE;


--
-- Name: media_assets fk_media_assets_owner_account; Type: FK CONSTRAINT; Schema: public; Owner: fourthitek_user
--

ALTER TABLE ONLY public.media_assets
    ADD CONSTRAINT fk_media_assets_owner_account FOREIGN KEY (owner_account_id) REFERENCES public.accounts(id);


--
-- Name: media_assets fk_media_assets_uploaded_by_account; Type: FK CONSTRAINT; Schema: public; Owner: fourthitek_user
--

ALTER TABLE ONLY public.media_assets
    ADD CONSTRAINT fk_media_assets_uploaded_by_account FOREIGN KEY (uploaded_by_account_id) REFERENCES public.accounts(id);


--
-- Name: support_ticket_message_attachments fk_support_message_attachments_media_asset; Type: FK CONSTRAINT; Schema: public; Owner: fourthitek_user
--

ALTER TABLE ONLY public.support_ticket_message_attachments
    ADD CONSTRAINT fk_support_message_attachments_media_asset FOREIGN KEY (media_asset_id) REFERENCES public.media_assets(id) ON DELETE CASCADE;


--
-- Name: support_ticket_message_attachments fk_support_message_attachments_message; Type: FK CONSTRAINT; Schema: public; Owner: fourthitek_user
--

ALTER TABLE ONLY public.support_ticket_message_attachments
    ADD CONSTRAINT fk_support_message_attachments_message FOREIGN KEY (message_id) REFERENCES public.support_ticket_messages(id) ON DELETE CASCADE;


--
-- Name: password_reset_tokens fkakpd9ro0vywgwa7hqmpbdurma; Type: FK CONSTRAINT; Schema: public; Owner: fourthitek_user
--

ALTER TABLE ONLY public.password_reset_tokens
    ADD CONSTRAINT fkakpd9ro0vywgwa7hqmpbdurma FOREIGN KEY (account_id) REFERENCES public.accounts(id);


--
-- Name: payments fkalvupkbf37ax1kxiayasm8k1x; Type: FK CONSTRAINT; Schema: public; Owner: fourthitek_user
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT fkalvupkbf37ax1kxiayasm8k1x FOREIGN KEY (id_order) REFERENCES public.orders(id);


--
-- Name: product_serials fkav9cg7x1panm2ubpv083dt0ga; Type: FK CONSTRAINT; Schema: public; Owner: fourthitek_user
--

ALTER TABLE ONLY public.product_serials
    ADD CONSTRAINT fkav9cg7x1panm2ubpv083dt0ga FOREIGN KEY (id_product) REFERENCES public.products(id);


--
-- Name: dealer_cart_items fkcagk50a3nx9bfp6h3rmklhjob; Type: FK CONSTRAINT; Schema: public; Owner: fourthitek_user
--

ALTER TABLE ONLY public.dealer_cart_items
    ADD CONSTRAINT fkcagk50a3nx9bfp6h3rmklhjob FOREIGN KEY (id_product_of_cart) REFERENCES public.product_of_carts(id);


--
-- Name: warranties fkci0njj9m6brk2651asf3j9sq; Type: FK CONSTRAINT; Schema: public; Owner: fourthitek_user
--

ALTER TABLE ONLY public.warranties
    ADD CONSTRAINT fkci0njj9m6brk2651asf3j9sq FOREIGN KEY (id_dealer) REFERENCES public.dealers(id_account);


--
-- Name: orders fkid19mswvi5bm1odjq76fex8c0; Type: FK CONSTRAINT; Schema: public; Owner: fourthitek_user
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT fkid19mswvi5bm1odjq76fex8c0 FOREIGN KEY (id_dealer) REFERENCES public.dealers(id_account);


--
-- Name: order_items fkj18ef1agdhkb3f8rmgrrgdbvu; Type: FK CONSTRAINT; Schema: public; Owner: fourthitek_user
--

ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT fkj18ef1agdhkb3f8rmgrrgdbvu FOREIGN KEY (id_order) REFERENCES public.orders(id);


--
-- Name: warranties fkky4pjnrpkslgsc9muwlkh46qb; Type: FK CONSTRAINT; Schema: public; Owner: fourthitek_user
--

ALTER TABLE ONLY public.warranties
    ADD CONSTRAINT fkky4pjnrpkslgsc9muwlkh46qb FOREIGN KEY (id_product_serial) REFERENCES public.product_serials(id);


--
-- Name: dealer_support_tickets fkn4dc6678fnjxy8qhh2qkqwdw; Type: FK CONSTRAINT; Schema: public; Owner: fourthitek_user
--

ALTER TABLE ONLY public.dealer_support_tickets
    ADD CONSTRAINT fkn4dc6678fnjxy8qhh2qkqwdw FOREIGN KEY (dealer_id) REFERENCES public.dealers(id_account);


--
-- Name: warranties fknj3buyv23flskyy0x54rgig8t; Type: FK CONSTRAINT; Schema: public; Owner: fourthitek_user
--

ALTER TABLE ONLY public.warranties
    ADD CONSTRAINT fknj3buyv23flskyy0x54rgig8t FOREIGN KEY (id_order) REFERENCES public.orders(id);


--
-- Name: dealers fko641ohm2rf04bjp0j1srkjjrw; Type: FK CONSTRAINT; Schema: public; Owner: fourthitek_user
--

ALTER TABLE ONLY public.dealers
    ADD CONSTRAINT fko641ohm2rf04bjp0j1srkjjrw FOREIGN KEY (id_account) REFERENCES public.accounts(id);


--
-- Name: product_serials fkqu6j7ct0qjcwgvfw075nns0in; Type: FK CONSTRAINT; Schema: public; Owner: fourthitek_user
--

ALTER TABLE ONLY public.product_serials
    ADD CONSTRAINT fkqu6j7ct0qjcwgvfw075nns0in FOREIGN KEY (id_order) REFERENCES public.orders(id);


--
-- Name: dealer_cart_items fksi02rgs4txl5fdgqa3xwadgpj; Type: FK CONSTRAINT; Schema: public; Owner: fourthitek_user
--

ALTER TABLE ONLY public.dealer_cart_items
    ADD CONSTRAINT fksi02rgs4txl5fdgqa3xwadgpj FOREIGN KEY (id_dealer) REFERENCES public.dealers(id_account);


--
-- Name: customers fkt0i38ckgik3ms8kxhfj0gckuk; Type: FK CONSTRAINT; Schema: public; Owner: fourthitek_user
--

ALTER TABLE ONLY public.customers
    ADD CONSTRAINT fkt0i38ckgik3ms8kxhfj0gckuk FOREIGN KEY (id_account) REFERENCES public.accounts(id);


--
-- Name: admins fkt42014jiwrst54d4lt9muogsb; Type: FK CONSTRAINT; Schema: public; Owner: fourthitek_user
--

ALTER TABLE ONLY public.admins
    ADD CONSTRAINT fkt42014jiwrst54d4lt9muogsb FOREIGN KEY (id_account) REFERENCES public.accounts(id);


--
-- Name: order_adjustments order_adjustments_order_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: fourthitek_user
--

ALTER TABLE ONLY public.order_adjustments
    ADD CONSTRAINT order_adjustments_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id);


--
-- Name: push_device_tokens push_device_tokens_account_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: fourthitek_user
--

ALTER TABLE ONLY public.push_device_tokens
    ADD CONSTRAINT push_device_tokens_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(id) ON DELETE CASCADE;


--
-- Name: refresh_token_sessions refresh_token_sessions_account_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: fourthitek_user
--

ALTER TABLE ONLY public.refresh_token_sessions
    ADD CONSTRAINT refresh_token_sessions_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

\unrestrict 2kzHEmICRHLQ7XAYyqLPmpBkdMooeiWxzsddRD2q6Hwrj8vpKb9IgkNrvxLXet1

