alter table accounts
    add column email_verified boolean;

alter table accounts
    add column email_verified_at timestamp(6) with time zone;

update accounts
set email_verified = false
where email_verified is null;

update accounts
set email_verified = true,
    email_verified_at = coalesce(updated_at, created_at, current_timestamp)
where email is not null
  and exists (
      select 1
      from admins
      where admins.id_account = accounts.id
  );

alter table accounts
    alter column email_verified set default false;

alter table accounts
    alter column email_verified set not null;

create table email_verification_tokens (
    account_id bigint not null,
    created_at timestamp(6) with time zone,
    expires_at timestamp(6) with time zone not null,
    used_at timestamp(6) with time zone,
    id bigint generated by default as identity,
    token_hash varchar(64) not null unique,
    primary key (id)
);

alter table if exists email_verification_tokens
    add constraint FK_email_verification_tokens_account
    foreign key (account_id) references accounts;
