alter table dealer_support_tickets
    add column if not exists assignee_id bigint;

alter table dealer_support_tickets
    add constraint fk_dealer_support_tickets_assignee
        foreign key (assignee_id) references admins(id_account);

create table if not exists support_ticket_messages (
    id bigint generated by default as identity primary key,
    ticket_id bigint not null,
    author_role varchar(32) not null,
    author_name varchar(255),
    internal_note boolean not null default false,
    message text not null,
    created_at timestamp(6) with time zone not null default current_timestamp,
    constraint fk_support_ticket_messages_ticket
        foreign key (ticket_id) references dealer_support_tickets(id) on delete cascade
);

create index if not exists idx_support_ticket_messages_ticket_created_at
    on support_ticket_messages (ticket_id, created_at);

insert into support_ticket_messages (ticket_id, author_role, author_name, internal_note, message, created_at)
select
    dst.id,
    'DEALER',
    coalesce(d.contact_name, d.business_name, a.username),
    false,
    dst.message,
    coalesce(dst.created_at, current_timestamp)
from dealer_support_tickets dst
join dealers d on d.id_account = dst.dealer_id
join accounts a on a.id = d.id_account
where not exists (
    select 1
    from support_ticket_messages stm
    where stm.ticket_id = dst.id
      and stm.author_role = 'DEALER'
      and stm.internal_note = false
      and stm.message = dst.message
);

insert into support_ticket_messages (ticket_id, author_role, author_name, internal_note, message, created_at)
select
    dst.id,
    'ADMIN',
    'Admin',
    false,
    dst.admin_reply,
    coalesce(dst.updated_at, dst.created_at, current_timestamp)
from dealer_support_tickets dst
where dst.admin_reply is not null
  and btrim(dst.admin_reply) <> ''
  and not exists (
      select 1
      from support_ticket_messages stm
      where stm.ticket_id = dst.id
        and stm.author_role = 'ADMIN'
        and stm.internal_note = false
        and stm.message = dst.admin_reply
  );
