CREATE TABLE public_content_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content_key VARCHAR(120) NOT NULL,
    locale VARCHAR(8) NOT NULL,
    payload TEXT NOT NULL,
    published BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE
);

CREATE UNIQUE INDEX uk_public_content_entries_key_locale
    ON public_content_entries (content_key, locale);
