create table audit_logs (
    id bigint generated by default as identity primary key,
    created_at timestamp(6) with time zone not null,
    actor varchar(255),
    actor_role varchar(255),
    action varchar(255) not null,
    request_method varchar(16) not null,
    request_path varchar(512) not null,
    entity_type varchar(255),
    entity_id varchar(255),
    ip_address varchar(128),
    payload jsonb
);

create index idx_audit_logs_created_at on audit_logs (created_at desc);
create index idx_audit_logs_actor on audit_logs (actor);
create index idx_audit_logs_entity on audit_logs (entity_type, entity_id);
