create table if not exists return_requests (
    id bigint generated by default as identity primary key,
    request_code varchar(64) not null unique,
    dealer_id bigint not null,
    order_id bigint not null,
    type varchar(64) not null,
    status varchar(64) not null,
    requested_resolution varchar(64) not null,
    reason_code varchar(128),
    reason_detail text,
    support_ticket_id bigint,
    requested_at timestamp(6) with time zone,
    reviewed_at timestamp(6) with time zone,
    received_at timestamp(6) with time zone,
    completed_at timestamp(6) with time zone,
    created_by varchar(255),
    updated_by varchar(255),
    created_at timestamp(6) with time zone not null default current_timestamp,
    updated_at timestamp(6) with time zone not null default current_timestamp,
    constraint fk_return_requests_dealer
        foreign key (dealer_id) references dealers(id_account),
    constraint fk_return_requests_order
        foreign key (order_id) references orders(id),
    constraint fk_return_requests_support_ticket
        foreign key (support_ticket_id) references dealer_support_tickets(id)
);

create index if not exists idx_return_requests_dealer_created_at
    on return_requests (dealer_id, created_at desc);

create index if not exists idx_return_requests_order_id
    on return_requests (order_id);

create index if not exists idx_return_requests_status
    on return_requests (status);

create table if not exists return_request_items (
    id bigint generated by default as identity primary key,
    request_id bigint not null,
    order_item_id bigint,
    product_id bigint not null,
    product_serial_id bigint not null,
    serial_snapshot varchar(255) not null,
    item_status varchar(64) not null,
    condition_on_request varchar(64),
    admin_decision_note text,
    inspection_note text,
    final_resolution varchar(64),
    replacement_order_id bigint,
    refund_amount numeric(19,2),
    credit_amount numeric(19,2),
    constraint fk_return_request_items_request
        foreign key (request_id) references return_requests(id) on delete cascade,
    constraint fk_return_request_items_order_item
        foreign key (order_item_id) references order_items(id),
    constraint fk_return_request_items_product
        foreign key (product_id) references products(id),
    constraint fk_return_request_items_serial
        foreign key (product_serial_id) references product_serials(id),
    constraint fk_return_request_items_replacement_order
        foreign key (replacement_order_id) references orders(id)
);

create index if not exists idx_return_request_items_request_id
    on return_request_items (request_id);

create index if not exists idx_return_request_items_serial_id
    on return_request_items (product_serial_id);

create index if not exists idx_return_request_items_status
    on return_request_items (item_status);

create table if not exists return_request_attachments (
    id bigint generated by default as identity primary key,
    request_id bigint not null,
    request_item_id bigint,
    url varchar(2048) not null,
    file_name varchar(255),
    category varchar(64) not null,
    constraint fk_return_request_attachments_request
        foreign key (request_id) references return_requests(id) on delete cascade,
    constraint fk_return_request_attachments_item
        foreign key (request_item_id) references return_request_items(id) on delete cascade
);

create index if not exists idx_return_request_attachments_request_id
    on return_request_attachments (request_id);

create table if not exists return_request_events (
    id bigint generated by default as identity primary key,
    request_id bigint not null,
    event_type varchar(128) not null,
    actor varchar(255),
    actor_role varchar(64),
    payload_json text,
    created_at timestamp(6) with time zone not null default current_timestamp,
    constraint fk_return_request_events_request
        foreign key (request_id) references return_requests(id) on delete cascade
);

create index if not exists idx_return_request_events_request_created_at
    on return_request_events (request_id, created_at);
