-- Granular RBAC: permission catalog + role_permissions join + internal staff roles.
-- Authorities are resolved fresh from DB on every request (Account.getAuthorities()),
-- so this migration only needs to populate data; no JWT/token format change.

create table if not exists permissions (
    id bigint generated by default as identity primary key,
    code varchar(64) not null unique,
    description varchar(255)
);

create table if not exists role_permissions (
    role_id bigint not null,
    permission_id bigint not null,
    primary key (role_id, permission_id),
    constraint fk_role_permissions_role
        foreign key (role_id) references roles(id) on delete cascade,
    constraint fk_role_permissions_permission
        foreign key (permission_id) references permissions(id) on delete cascade
);

create index if not exists idx_role_permissions_role on role_permissions (role_id);

-- Ensure base + internal staff roles exist. ADMIN/SUPER_ADMIN/DEALER may already have been
-- created lazily by Java initializers on an existing database, so each insert is guarded.
insert into roles (name, description)
    select 'SUPER_ADMIN', 'Super admin role'
    where not exists (select 1 from roles where name = 'SUPER_ADMIN');
insert into roles (name, description)
    select 'ADMIN', 'Admin role'
    where not exists (select 1 from roles where name = 'ADMIN');
insert into roles (name, description)
    select 'DEALER', 'Default dealer role'
    where not exists (select 1 from roles where name = 'DEALER');
insert into roles (name, description)
    select 'SALES', 'Internal staff: sales / order operations'
    where not exists (select 1 from roles where name = 'SALES');
insert into roles (name, description)
    select 'WAREHOUSE', 'Internal staff: warehouse / serial & inventory'
    where not exists (select 1 from roles where name = 'WAREHOUSE');
insert into roles (name, description)
    select 'ACCOUNTANT', 'Internal staff: accounting / payment & reconciliation'
    where not exists (select 1 from roles where name = 'ACCOUNTANT');
insert into roles (name, description)
    select 'CONTENT_EDITOR', 'Internal staff: content / catalog & SEO'
    where not exists (select 1 from roles where name = 'CONTENT_EDITOR');

-- Permission catalog (24 codes). The permissions table is created by this migration,
-- so a plain insert is safe — no rows can pre-exist.
insert into permissions (code, description) values
    ('orders.read', 'View orders'),
    ('orders.approve', 'Approve an order (PENDING -> CONFIRMED)'),
    ('orders.process', 'Advance order processing (CONFIRMED -> PROCESSING -> SHIPPING -> COMPLETED)'),
    ('orders.cancel.review', 'Review dealer cancel requests (approve / reject)'),
    ('orders.payment.confirm', 'Record / confirm order payments'),
    ('serials.read', 'View product serials'),
    ('serials.write', 'Mutate serials: import, status, RMA, delete'),
    ('serials.assign', 'Assign serials to an order'),
    ('warranties.read', 'View warranties'),
    ('warranties.write', 'Mutate warranty status'),
    ('returns.read', 'View return requests'),
    ('returns.write', 'Process return requests'),
    ('dealers.read', 'View dealers'),
    ('dealers.write', 'Mutate dealer profile / status'),
    ('support.read', 'View support tickets'),
    ('support.write', 'Reply to / update support tickets'),
    ('products.write', 'Mutate products'),
    ('blogs.write', 'Mutate blogs'),
    ('content.write', 'Mutate public content sections'),
    ('media.write', 'Upload / mutate media assets'),
    ('discounts.write', 'Mutate wholesale discount rules'),
    ('reports.read', 'View / export reports'),
    ('notifications.read', 'View admin notifications'),
    ('dashboard.read', 'View the admin dashboard');

-- SUPER_ADMIN + ADMIN: all 24 codes (full operational access; backward compatible).
insert into role_permissions (role_id, permission_id)
    select r.id, p.id
    from roles r
    cross join permissions p
    where r.name in ('SUPER_ADMIN', 'ADMIN')
      and not exists (
          select 1 from role_permissions rp
          where rp.role_id = r.id and rp.permission_id = p.id
      );

-- SALES.
insert into role_permissions (role_id, permission_id)
    select r.id, p.id
    from roles r
    join permissions p on p.code in (
        'orders.read', 'orders.approve', 'orders.process', 'orders.cancel.review',
        'dealers.read', 'dealers.write', 'returns.read', 'returns.write',
        'support.read', 'support.write', 'discounts.write',
        'reports.read', 'dashboard.read', 'notifications.read'
    )
    where r.name = 'SALES'
      and not exists (
          select 1 from role_permissions rp
          where rp.role_id = r.id and rp.permission_id = p.id
      );

-- WAREHOUSE.
insert into role_permissions (role_id, permission_id)
    select r.id, p.id
    from roles r
    join permissions p on p.code in (
        'serials.read', 'serials.write', 'serials.assign',
        'warranties.read', 'warranties.write', 'returns.read', 'returns.write',
        'orders.read', 'orders.process', 'dashboard.read', 'notifications.read'
    )
    where r.name = 'WAREHOUSE'
      and not exists (
          select 1 from role_permissions rp
          where rp.role_id = r.id and rp.permission_id = p.id
      );

-- ACCOUNTANT.
insert into role_permissions (role_id, permission_id)
    select r.id, p.id
    from roles r
    join permissions p on p.code in (
        'orders.read', 'orders.payment.confirm',
        'reports.read', 'dashboard.read', 'notifications.read'
    )
    where r.name = 'ACCOUNTANT'
      and not exists (
          select 1 from role_permissions rp
          where rp.role_id = r.id and rp.permission_id = p.id
      );

-- CONTENT_EDITOR.
insert into role_permissions (role_id, permission_id)
    select r.id, p.id
    from roles r
    join permissions p on p.code in (
        'products.write', 'blogs.write', 'content.write', 'media.write',
        'dashboard.read', 'notifications.read'
    )
    where r.name = 'CONTENT_EDITOR'
      and not exists (
          select 1 from role_permissions rp
          where rp.role_id = r.id and rp.permission_id = p.id
      );
